[package]
name = "promo-tg-mini-app"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
serde = { version = "1.0.219", features = ["derive"] }
tokio = {  version = "1.44.1", features = ["rt", "macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.19"
